add lengthFilter
GoodbyteCo/Letterboxd-Watchlist-Picker pull request #79
Opened 2021-04-01 06:11 UTC by HoloPollock

2021-04-01 06:15 UTC, HoloPollock commented
only backend for now

2021-04-01 11:12 UTC, maxkele commented on api/index.go
> +				userFilm, err = scrapefunc(users, false, true)
Is this supposed to be done twice?

2021-04-01 11:37 UTC, HoloPollock commented on api/index.go
> +				userFilm, err = scrapefunc(users, false, true)
No good catch

2021-04-03 19:01 UTC, qjack001 requested changes
use 60min as cutoff

2021-04-03 19:04 UTC, HoloPollock commented on api/index.go
> +const FEATURELENGTH = 80
Cool I agree

2021-04-03 19:04 UTC, HoloPollock commented on api/index.go
> +}
Yah this was a hack of using partial funcs to have less gross if statements

2021-04-06 03:01 UTC, HoloPollock commented
also if anyone wants to do the front end go ahead

2021-04-06 04:30 UTC, qjack001 approved these changes

2021-04-06 05:01 UTC, HoloPollock commented
No one merge yet I wanna do testing cause I change how scraping works

2021-04-07 06:44 UTC, HoloPollock commented
the speed slowed down with new changed I want to see if I can fix before merging

2021-04-07 06:54 UTC, HoloPollock commented
I cheated and increased the memory and it worked

2021-04-07 06:55 UTC, HoloPollock commented
still wanna do some more tests

2021-04-07 07:02 UTC, qjack001 commented
Could I give you the options in a comma-seperated `ignore` param? Like: `/?users=qjack&ignore=unreleased,shorts,feature&iintersect=true`? Ignore unreleased films if `unreleased` is present, ignore short films if `shorts` is present, ignore feature-length if `feature` is present.

2021-04-07 07:06 UTC, HoloPollock commented
> Could I give you the options in a comma-seperated `ignore` param? Like: `/?users=qjack&ignore=unreleased,shorts,feature&iintersect=true`? Ignore unreleased films if `unreleased` is present, ignore short films if `shorts` is present, ignore feature-length if `feature` is present.

Yah that should work I can make that happen

2021-04-07 07:08 UTC, qjack001 commented
> > Could I give you the options in a comma-seperated `ignore` param? Like: `/?users=qjack&ignore=unreleased,shorts,feature&iintersect=true`? Ignore unreleased films if `unreleased` is present, ignore short films if `shorts` is present, ignore feature-length if `feature` is present.
> 
> Yah that should work I can make that happen

yay

2021-04-13 06:50 UTC, HoloPollock commented
so its done and works now I do think we may want to merge this in to the UI branch to test it works with `ignore=unreleased,shorts,feature` it should I tested with postman but still should test integration @qjack001

2021-04-13 06:52 UTC, HoloPollock commented
also feel free to look at code for stupid things I did

2021-04-13 07:25 UTC, HoloPollock commented
hey so I know why its slower the new page I'm loading is way bigger so it makes it way slower to do may not be worth

2021-04-13 07:25 UTC, HoloPollock commented
hey so I know why its slower the new page I'm loading is way bigger so it makes it way slower to do may not be worth

2021-04-13 07:25 UTC, HoloPollock commented
hey so I know why its slower the new page I'm loading is way bigger so it makes it way slower to do may not be worth

2021-04-13 07:25 UTC, HoloPollock commented
hey so I know why its slower the new page I'm loading is way bigger so it makes it way slower to do may not be worth

2021-04-13 07:25 UTC, HoloPollock commented
I dont know another way to get the time though

2021-04-13 07:29 UTC, HoloPollock commented
its. difference between loading this [site ](https://letterboxd.com/ajax/poster/film/maggies-plan/menu/linked/125x187/) and the full detail page ex [this](https://letterboxd.com/film/maggies-plan/)

2021-04-13 07:30 UTC, HoloPollock commented
lol letterbox please give me API

2021-04-13 07:35 UTC, HoloPollock commented
the only thing I can think of to keep this is only load the page when the check boxes are checked

2021-04-13 16:24 UTC, qjack001 commented
> the only thing I can think of to keep this is only load the page when the check boxes are checked

Only use the heavier page if the `ignore` parameter was given `shorts` or `feature`, yes.

2021-04-13 16:28 UTC, qjack001 commented
> so its done and works now I do think we may want to merge this in to the UI branch to test it works with `ignore=unreleased,shorts,feature` it should I tested with postman but still should test integration @qjack001 

Once you make the change above, I would just merge into main. It should have no noticeable effect on the site (as it is now). My PR should get the update too, since I believe it uses the prod endpoint.

2021-04-22 05:18 UTC, qjack001 commented
poke

2021-04-22 12:45 UTC, maxkele approved these changes

2021-05-06 20:51 UTC, HoloPollock commented
@qjack001 should be good to merge pls check

2021-05-06 20:54 UTC, HoloPollock commented
also closes #69

2021-05-07 06:29 UTC, qjack001 approved these changes
great

2021-05-07 06:29 UTC, qjack001 commented on api/index.go
> +		ignoreing = whatToIgnore(ignore[0])
lol "ignoreing"

2021-05-07 06:29 UTC, qjack001 commented on api/index.go
> +		lenght := e.ChildText("p.text-footer")
"lenght"

2021-05-07 06:36 UTC, merged